apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: example=ghcr.io/md-jakir/gitops-cert-level-2-examples
    #argocd-image-updater.argoproj.io/image-list: example=ghcr.io/codefresh-contrib/gitops-cert-level-2-examples
    #argocd-image-updater.argoproj.io/example.update-strategy: latest
    argocd-image-updater.argoproj.io/image-list
spec:
  project: default

  source:
    #repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    repoURL: https://github.com/md-jakir/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/qa/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
